pipeline{
    agent any
      tools{
    maven 'M2_HOME'
   }
    stages{
        stage("Maven"){
            steps{
        sh 'mvn clean'
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
            }
            
        }
        stage("upload artifacts"){
            steps{
        sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T target/bio.jar "http://ec2-34-238-250-52.compute-1.amazonaws.com:8081/artifactory/geolocation1/geo1/bio_${BUILD_ID}.jar"'
"        
            }
        }
    }
}